### PR TITLE
Add compare_proxy() to path

### LINKED ISSUE #73: Suggestion:  indicate use of proxy in output
I'm updating `rgl`, and have changed the internal layout of some objects.  I have an `all.equal()` method for these objects that knows to ignore the irrelevant changes, but `testthat::expect_equal()` doesn't use that.  That's a bit irritating, but I can work around it by adding a `compare_proxy` method that canonicalizes objects.  However, output is now slightly misleading.  For example, if I have two objects with components in a different order, the report doesn't reflect that:

``` r
library(rgl)
x <- cube3d()
names(x)
#> [1] "vb"        "material"  "normals"   "texcoords" "ib"
y <- x
y$vb2 <- y$vb
y$vb <- NULL
waldo::compare(x, y)
#> `names(old)`: "ib" "material" "vb" 
#> `names(new)`: "ib" "material" "vb2"
#> 
#> `old$vb` is a double vector (-1, -1, -1, 1, 1, ...)
#> `new$vb` is absent
#> 
#> `old$vb2` is absent
#> `new$vb2` is a double vector (-1, -1, -1, 1, 1, ...)
```

<sup>Created on 2021-04-14 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

Notice that the names of `x` don't match `names(old)`, because we're really looking at `compare_proxy(x)`.

I think it would be sufficient to add something like:

    Using proxies for comparison:

at the start.

### PR DESCRIPTION
**Pull request by hadley**
Fixes #73

@dmurdoch just occurred to me that the obvious way to report the use of a proxy is in the path. I need to clean up the implementation a little, but what do you think of the results?

### CODE REVIEW

**Comment by dmurdoch** [comment]
Looks good.

**Comment by hadley** [comment]
@jimhester @dmurdoch thinking about this more, I think it makes even more sense for `compare_proxy()` to be in charge of modifying the path. Unfortunately this changes the generic so will break any packages that currently provide a `compare_proxy()` method; as far as I can tell this is just vroom and rgl currently, so I think it is feasible to make this change.  I'll send you both a PR to conditionally register different methods, but it will require some work on your end since you'll need to do a CRAN release before I can submit waldo. My sense is that it's worth this change, but I don't want to impose extra work on your both before asking first.

cc @nealrichardson since you're the only other person who has looked at this code

**Comment by dmurdoch** [comment]
I wouldn't be a big deal to change rgl's `compare_proxy`.  I'm getting ready for a CRAN release anyway.

**Comment by nealrichardson** [comment]
Makes sense to me. I haven't yet switched `arrow`'s tests to use this comparison yet (though I'm curious to pick it up now!), so no concerns from me about changing the API.

**Comment by jimhester** [comment]
LGTM

**Comment by dmurdoch** [comment]
The devel version of `rgl` now works with CRAN `waldo` and this PR.  Any reason to delay submitting the update to CRAN?

**Comment by hadley** [comment]
Not that I know of. I'll merge this PR shortly.

**Pull request merged**
